spring.application.name=notification-service

server.port=8082

spring.kafka.bootstrap-servers=localhost:9092

spring.kafka.consumer.group-id=notification-group
spring.kafka.consumer.auto-offset-reset=earliest

spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JacksonJsonDeserializer

spring.kafka.consumer.properties.spring.json.trusted.packages=*

#GMAIL CONFIG

spring.mail.host=smtp.gmail.com
spring.mail.port=587

spring.mail.username=shauryashaan01@gmail.com
spring.mail.password={GMAIL_GENERATED_PASSCODE}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

#Twilio

# SMS
twilio.account.sid={TWILIO_ACCOUNT_SID}
twilio.auth.token={TWILIO_AUTH_TOKEN}
twilio.phone.number={TWILIO_MOBILE}

#WhatsApp
twilio.whatsapp.number={whatsapp:TWILIO_WHATSAPP_NUMBER}



